name: Scheduled Upstream Merge
on: 
  schedule:
    - cron: '38 */6 * * *'
  workflow_dispatch:

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream             # set the branch to merge to
          fetch-depth: 0            # get all changes
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          username: github-actions[bot]         # set the user name for git commits
          useremail: github-actions[bot]@users.noreply.github.com  # set the user email for git commits
          upstream: austinhuang0131/joinmatrix  # set the upstream repo
          upstream-branch: main                 # set the upstream branch to merge from
          branch: upstream                      # set the branch to merge to
